services:
  db:
    image: mysql:8.0
    platform: linux/arm64 # Ensure compatibility with Mac M1
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: MyWebApiDb
      MYSQL_USER: apiuser
      MYSQL_PASSWORD: api123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
