version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: MyWebApi
    restart: always
    ports:
      - "80:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=server=db;database=MyWebApiDb;user=apiuser;password=api123
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: MyWebApiDb
      MYSQL_USER: apiuser
      MYSQL_PASSWORD: api123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
